# Site settings
title: noobit -- freelance your it
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The DNA for your next Webproject - Stay tuned!
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://noobit.github.io" # the base hostname & protocol for your site
twitter_username: noobit
github_username:  noobit

# Build settings
markdown: kramdown
