# Site settings
title: noobit -- agil. robust. responsive. sicher.
email: roman.rauch@alumni.tu-berlin.de
description: > #Website, responsive, Wordpress, HTML5, CSS3
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://noobit.github.io" # the base hostname & protocol for your site
twitter_username: noobit
github_username:  noobit

# Build settings
markdown: kramdown
